version: "3.8"

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    networks:
      - inception
    expose:                         
      - "3306"
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wps:/var/wwww/wordpress
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    networks:
      - inception
    env_file:
      - .env
    expose:
      - "9000"
    depends_on:
      - mariadb
    volumes:
      - wps:/var/wwww/wordpress

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/skhaliff/data/mariadb
  wps:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/skhaliff/data/wordpress
     
networks:
  inception:
    name: inception     